ARMmbed/ble

- services/URIBeaconConfigService.h
remove methods that update while running config service, this is an unlikely use case
fix characteristics table to include all
rename const UUIDs to fit naming style
don't assume URI is a URL and remove encoding methods
add defaults, which are used for reset, as distrinct from params
Use new style of readonly writeonly characteristic declarations
let caller manage the advertising for both Config mode and Beacon
astyle formatting
> Uribeacon update

- services/iBeaconService.h
making iBeacons is really really really hard
The iBeacon example program on the website has code that looks like this:
```C++
/**
* The Beacon payload (encapsulated within the MSD advertising data structure)
* has the following composition:
* 128-Bit UUID = E2 0A 39 F4 73 F5 4B C4 A1 2F 17 D1 AD 07 A9 61
* Major/Minor  = 0000 / 0000
* Tx Power     = C8 (-56dB)
*/
const static uint8_t iBeaconPayload[] = {
0x4C, 0x00, // Company identifier code (0x004C == Apple)
0x02,       // ID
0x15,       // length of the remaining payload
0xE2, 0x0A, 0x39, 0xF4, 0x73, 0xF5, 0x4B, 0xC4, // location UUID
0xA1, 0x2F, 0x17, 0xD1, 0xAD, 0x07, 0xA9, 0x61,
0x00, 0x00, // the major value to differentiate a location
0x00, 0x00, // the minor value to differentiate a location
0xC8        // 2's complement of the …
```
> added API for creating iBeacons

- public/BLEDevice.h
- public/GattCharacteristicCallbackParams.h
- public/GattServer.h
Added a callback for when a characteristic is being read. This is necessary for characteristics whose values are generated on demand.
> Added callback on characteristic reads

- public/GattAttribute.h
Added support for attributes with dynamic lengths. This is necessary to support some non-standard characteristics.
> Extended attribute length handling to support dynamic length.

- module.json
We should probably pull in mbedOS / mbed-classic based on a target dependency, but using this gets things building on mbed-classic for now.
> use mbed-classic as mbed dependency

- module.json
Reverts mbedmicro/BLE_API#45
wanted to merge to develop first.
> Revert "use mbed-classic as mbed dependency"

- ble/GattCharacteristic.h
- ble/GattService.h
- Forwards the optional `descriptors` and `numDescriptors` arguments to base constructor
- Fixes typo in GattService constructor comment header
> expose descriptors optional arg in derived GattChar. constructors

- ble/DiscoveredCharacteristic.h
This second pull request changes the DiscoveredCharacteristic API to have `getUUID()` as opposed to only `getShortUUID()`. Otherwise you can't have long-UUID characteristics... :smile: It needs the corresponding pull request in `nRF51822`.
> Change DiscoveredCharacteristic API to return long or short UUIDs.

- ble/services/EddystoneService.h
reverted eddystone service to pre-existing version that is known working. 
it works
it does not play nice with other services, as of right now if you use eddystone it is the only service you can have on your device. Will revisit this in the near future to fix. 
* added config flags for uid and url being set to true (due to improper if else if statements they weren't being handled correctly)
* removed API to swap out adv frames individually as it was failing, will revisit and debug in the future
* separated out debug messages so they can be enabled selectively
> Eddystone Service Working

- ble/services/EddystoneConfigService.h
- ble/services/EddystoneService.h
This is the result of my work with Google to enable the eddystone beacon service and the eddystone config service.
> Adding Eddystone Support

- module.json
This change will allow developers to build  BLE applications on the st-ble-shield. The shield reference is x-nucleo-idb0xa1.
If you want to build software on this board, you should use the target "frdm-k64f-st-ble-gcc" which is not yet on the yotta registry but is available at https://github.com/ARMmbed/target-frdm-k64f-st-ble-gcc.git .
> Add st-ble-shield as a possible target dependency.

- ble/services/EddystoneConfigService.h
- ble/services/EddystoneService.h
Introduced a fix for defect IOTSFW-1058 that caused the
BLE_EddystoneBeaconConfigService example in ARMmbed/ble-examples repo to fail.
Refer to JIRA defect for more details.
> Introduced fix for defect IOTSFW-1058

- ble/services/HealthThermometerService.h
Modified the HealthThermometer header file to include BLE.h from
ble/BLE.h.
> Fixed include problem in HealthThermometer header

- ble/BLE.h
- ble/BLEInstanceBase.h
- ble/blecommon.h
- module.json
- source/BLE.cpp
There's a completion callback.
This will require corresponding change to ble-nrf51822. Demos will need to be adapted.
Please review @pan- @andresag01 @marcuschangarm @jaustin
> BLE::init() now takes in a callback paramter

- ble/FunctionPointerWithContext.h
This patch reduce the memory consumed by FunctionPointerWithContext  instances. 
The original size of a FunctionPointerWithContext  is 32 bytes, with this patch it goes down to 20bytes. With this change, it is possible to save 24 bytes by GattCharacteristic. 
The idea is simple, instead of storing a function pointer, an object and a pointer to a member function it only store the function pointer OR the object and the pointer to the member function.
An undefined pointer to member function type is used to calculate the true size of the biggest possible pointer to member function and align properly the pointer to member stored.
> Reduce the memory consumed by FunctionPointerWithContext instances

- ble/services/EddystoneConfigService.h
- ble/services/EddystoneService.h
Fix EddystoneService to make use of beaconPeriod values written when in configuration mode. Also, change default for TLM Temperature to 0x8000 and BatteryVoltage to 0x0 to conform to the eddystone specification.
> Fix beaconPeriod and defaults for voltage/temp

- ble/BLE.h
- ble/BLEInstanceBase.h
- ble/FunctionPointerWithContext.h
- source/BLE.cpp
please review: @pan- @marcuschangarm 
this is urgent.
> BLE::init() should also be able to take an <object, member> tuple for its callback

- ble/GapAdvertisingData.h
Resubmission of https://github.com/ARMmbed/ble/pull/101
> Changed GapAdvertisingData.addData to take current fields into account when adding data.

- ble/CallChainOfFunctionPointersWithContext.h
- ble/DiscoveredCharacteristic.h
- ble/FunctionPointerWithContext.h
- ble/Gap.h
- ble/GattClient.h
- ble/GattServer.h
- ble/SafeBool.h
- ble/ServiceDiscovery.h
- source/DiscoveredCharacteristic.cpp
This pull request improve `CallChainOfFunctionPointersWithContext`, `FunctionPointerWithContext` and provide a way to unregister callbacks previously registered in a callchain.
Changes in `FunctionPointerWithContext` are not minor, goals were to provide function pointer semantic and value semantic: 
- support of copy constructor and assignement
- support of equality operator
- support of function call operator
- support of safe comparison to bool
- call does *not* call the `next` `FunctionPointerWithContext`, it is not its responsibility any more. This change can be seen as a breaking one. `FunctionPointerWithContext` needs to handle less things, is it a list, a node of a list, a call chain ? Unfortunately, mixing responsibilities hurt and I was forced to make this change if I wanted to …
> Remove persistant callbacks

- CONTRIBUTING.md
- DOXYGEN_FRONTPAGE.md
- README.md
- ble/blecommon.h
- doxygen/.gitignore
- doxygen/Makefile
- doxygen/ble.doxyfile
- doxygen/main.md
@rgrover added Doxygen support in commits 04d10f65474c22480501ced491f4a32af746346f and f72edf4d503903c101c75843a9c3f32f8a2bbd44.
This is great! IMO, it is a must have for an API :smirk:
I refactored all Doxygen stuff to a specific folder (to keep some consistency, I did the same as [mbedtls](https://github.com/ARMmbed/mbedtls/tree/development/doxygen)) . I added a Makefile to generate the doc automatically and fix some typos (especially wrong Markdown syntax).
This is the very first Doxygen output and the documentation is not well formatted yet. A lot of polishing is needed... I am not native English speaker, so I cannot correct the doc or add Doxygen pages.
What we can do is publishing automatically the Doxygen documentation (for release versions) to `gh-page` so the doc is available …
> First Doxygen output

- ble/services/EddystoneConfigService.h
- ble/services/EddystoneService.h
For compatibility reasons in mbed classic, the old Eddystone implementation under ble/services (i.e. EddystoneConfigService.h and EddystoneService.h) is reintroduced. However, attempting to use this files with generate a deprecation warning at compile time with the URL of the ble-example/BLE_EddystoneService.
> Reintroduce old Eddystone with deprecated warnings

- ble/GattAttribute.h
- ble/GattCharacteristic.h
In previous versions of BLE_API the GattCharacteristic initLen parameter is named minLen as well. When the characteristic is committed to the SoftDevice the value of initial length is also used as the minimum length of the characteristic value. Furthermore, the test (max_length == min_length) is used to determine whether the characteristic value has variable length. This is slightly confusing and also causes problems if the user wishes to use a characteristic with variable length but the initial length is equal to max length.
To solve this problem the characteristic is now always committed to the SoftDevice as variable. Furthermore, the API only maintains the current length and the max length i.e. the field initialLen in the GattAttribute is removed. Finally, the constructor for the …
> Separate the concept of minlen and len in GattAttr

- ble/GattAttribute.h
- ble/GattCharacteristic.h
Previously the concepts of initLength and lenth were clearly separated. However, this was at the cost of registering all characteristics in the SoftDevice as having variable length. Clearly, this is not the desired behaviour. Therefore, an additional field '_hasVariableLen' is added to the GattAttribute to address the problem. Also, the GattAttribute and GattCharacteristic constructors have been modified to take a boolean that sets '_hasVariableLen'.
@rgrover
> Allow GattAttributes to have variable length

- ble/Gap.h
Fix documentation for getMinAdvertisingInterval() and getMinNonConnectableAdvertisingInterval() functions in Gap.h
> Fix documentation for advertising interval getters

- ble/BLE.h
- ble/BLEProtocol.h
- ble/Gap.h
While adding support for white-listing, I realized that a lot of core types, such as Address_t, are currently residing in Gap.h but are more abstract than Gap. They should be abstracted out of Gap otherwise they will result in circular dependencies.
I've also taken the opportunity to cleanup the types and add some documentation.
internal-ref: IOTSFW-1416
@pan- @marcuschangarm @andresag01 @LiyouZhou
> Extract Adress related types from Gap.h into BLEProtocol.h

- ble/Gap.h
> transparenly support existing applications which may have used Gap::ADDR_TYPE_*

- ble/Gap.h
- ble/GattClient.h
- ble/GattServer.h
- ble/SecurityManager.h
Add an onShutdown() function to Gap, GattClient, GattServer and
SecurityManager. The callbacks are added to a private callback chain in each of
the instances. The callbacks will be executed inside each object's reset()
function BEFORE the state of the instance is cleared. The developers of the
platform-specific implementation must call the parent class' reset() function
for the callbacks to be executed.
Finally, an onShutdown() function that returns the shutdown callchain is added
to allow detaching callbacks.
> Add onShutdown to register callbacks

- ble/GapAdvertisingData.h
- ble/blecommon.h
@rgrover @LiyouZhou @pan-: It is slightly unclear which one is the deprecated one, but I removed the one in blecommon.h because all the BLE API seems to be using the appearance values in GapAdvertisingData.h.
> Remove deprecated appearance enum from blecommon.h

- ble/blecommon.h
Add an additional error code to the ble_error_t enum to describe a failure
state caused by the internal platform-specific stack. This state was not
described by any of the existing error codes.
@rgrover @pan-
> Add BLE_ERROR_INTERNAL_STACK_FAILURE error code

- source/DiscoveredCharacteristic.cpp
Clean up the code by removing white spaces and adding statements to suppress
unused-parameter compiler warnings.
@rgrover @LiyouZhou @pan-
> Clean up code in DiscoveredCharacteristic.cpp

- ble/Gap.h
- ble/GapAdvertisingData.h
Modify the functions addData() and updateData() to correctly update the payload
information for a specified AD type if that type was already present in the
payload. For addData() if the AD type is not found, it is added to the payload.
In contrast, in updateData() if the AD type is not found an error is returned.
Documentation was updated accordingly.
@rgrover @pan- @LiyouZhou
> Modify functions that manipulate adv payload

- ble/Gap.h
- ble/deprecate.h
- module.json
for change from Gap:AddressType_t to BLEProtocol::AddressType_t
@pan- @andresag01  please review.
> Hotfix for backward compatibility

- ble/BLE.h
- ble/BLEProtocol.h
- ble/Gap.h
This is the finilised experimental API that introduces support for
whitelisting. The changes are focused in Gap and introduces the following
functions, that are expected to be implemented by each of the vendor specific
glue code (e.g. ble-nrf51822 module):
- getMaxWhitelistSize(): Get the maximum whitelist size, this can be set by
using a yotta config definition.
- getWhitelist(): Gets a copy of the internal whitelist containing BLE
addresses.
- setWhitelist(): Replace the whitelist with new addresses.
- setAdvertisingPolicyMode(), setScanningPolicyMode() and
setInitiatorPolicyMode(): Functions used to set the relevan policy filter
mode as described in the BLE Specification v4.2 Vol 6, Part B, Section 4.2.1.
- getAdvertisingPolicyMode(), getScanningPolicyMode() and …
> Whitelisting experimental API

- ble/SecurityManager.h
The new API is added to the Security Manager. Its declaration is as follows:
virtual ble_error_t getAddressesFromBondTable(Gap::Whitelist_t &addresses)
The resulting Whitelist_t structure can then be used as the actual whitelist
passes to Gap::setWhitelist().
Note that for peers that have private resolvable addresses, then an address of
the same type will be returned.
@pan-
> Add API to get addresses of peers in bond table

- ble/Gap.h
The BLE API was not updating the Gap internal state when the advertising stops
because of a user timeout. This commit fixes the issue by updating the internal
state structure in Gap just before the registered callbacks are notified of the
advertising timeout.
@pan-
> Update Gap state after advertising times out

- ble/Gap.h
Update the Gap::state in Gap itself rather than the implementation. There is an associated pull request in ble-nrf51822: https://github.com/ARMmbed/ble-nrf51822/pull/108.
@pan-
> Update Gap state in startAdvertising()

- ble/Gap.h
- ble/GattClient.h
- ble/GattServer.h
- ble/SecurityManager.h
Change onShutdown(obj, func) definition for func so that it takes the same
arguments as function-only callbacks rather than void.`
@pan-
> Change onShutdown(obj, func) definition

- ble/Gap.h
Invalid advertising payloads are no longer committed to the local copy of the advertising and scan payloads in BLE API before the contents are checked by the underlying stack. The Gap member functions changed are:
* accumulateAdvertisingPayload(flags)
* accumulateAdvertisingPayload(appearance)
* accumulateAdvertisingPayloadTxPower(power)
* accumulateAdvertisingPayload(type, data, length)
* updateAdvertisingPayload(type, data, length)
* setAdvertisingPayload(newPayload)
* accumulateScanResponse(type, data, length)
Furthermore, startAdvertising() no longer sets the payload in the underlying stack because the payload is set every time it is updated. Finally, the shorthand private member setAdvertisingData(void) is removed from Gap as it is redundant.
@pan-
> Invalid adv payloads are not committed before checking

- ble/BLE.h
- ble/BLEInstanceBase.h
- source/BLE.cpp
- source/BLEInstanceBase.cpp
The mechanism is quite simple:
* user code can process all events pending in the internal BLE stack by
calling the function BLE::processEvent.
* user code can be notified when an event become available and the event
stack has to be processed. The notification is issued by the port of
mbed BLE.
For mbed os 3 and mbed classic, this doesn't change the existing behavior.
> Add an interface which allows user code to customise the way BLE events are processed.
